{% set name = "jellyfish" %}
{% set version = "0.11.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "654f2b1543b9927c4429bd5d66f98d1f47e6eb9a4e56212e1907fb4eea258c5a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
# Also skip for ARM64 due to Maturin no support for now, and when ppc64le AND python<3.10
  skip: True  # [py<37 or arm64 or (py<310 and ppc64le)]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=0.14,<0.15
    - pip
    - python
  run:
    - python

test:
  imports:
    - jellyfish
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jamesturk/jellyfish
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A library for doing approximate and phonetic matching of strings.
  dev_url: https://github.com/jamesturk/jellyfish
  doc_url: https://jamesturk.github.io/jellyfish/

extra:
  recipe-maintainers:
    - blabalme
    - anthchirp
    - thewchan
