{% set name = "jellyfish" %}
{% set version = "1.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "2a2eec494c81dc1eb23dfef543110dad1873538eccaffabea8520bdac8aecbc1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
# Also skip for when ppc64le AND python<3.10 due to Maturin no support for now
  skip: true  # [py<37 or (py<310 and ppc64le)]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin >=0.14,<2                      # [build_platform != target_platform]
  host:
    - maturin >=0.14,<2
    - pip
    - python
  run:
    - python

test:
  imports:
    - jellyfish
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jamesturk/jellyfish
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A library for doing approximate and phonetic matching of strings.
  dev_url: https://github.com/jamesturk/jellyfish
  doc_url: https://jamesturk.github.io/jellyfish/

extra:
  recipe-maintainers:
    - blabalme
    - anthchirp
    - thewchan
