{% set name = "jellyfish" %}
{% set version = "0.7.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "cb09c50d7e2bb7b926fc7654762bc81f9c629e0c92ae7137bf22b34f39515286" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - jellyfish

about:
  home: http://github.com/jamesturk/jellyfish
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'a library for doing approximate and phonetic matching of strings.'
  dev_url: http://github.com/jamesturk/jellyfish
  doc_url: https://jellyfish.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - blabalme
