{% set name = "jellyfish" %}
{% set version = "0.8.9" %}
{% set bundle = "tar.gz" %}
{% set hash = "90d25e8f5971ebbcf56f216ff5bb65d6466572b78908c88c47ab588d4ea436c2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - {{ compiler('c') }}
    - pip
    - python
  run:
    - python

test:
  imports:
    - jellyfish
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jamesturk/jellyfish
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: a library for doing approximate and phonetic matching of strings.
  dev_url: https://github.com/jamesturk/jellyfish
  doc_url: https://jellyfish.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - blabalme
    - anthchirp
