travis:
  secure:
    BINSTAR_TOKEN: ivDt+pLFCooTB4VWN7piCJWFgFE4tEyFGMfn/c6C6m9upOz4Zt3gE7WX2+cnqQuID4MUWhSybvGiFSkUjlXZIyPPyy430N7bHOLWI78P9iVImRfCJl5TF0oiF09ejZKOLaOR4UgDnkGwDR5NGp2CzlsabH+UlUo4/Zy5yJCv7mt1yCrz9NXYfy5tm6IJtFu1evAuJHR+L/BE2jJoGgoXUCK0dhnLX4YD8YxW13E6b4FwWIdAF1H9/AvmJ3hDzmkd3jOvMM9XKCgFbsIxr1E5B+pa84GwcfhSN4PL/Kk91sLfUREPZbYKggWs2vfJchkSyS32egLjfCljD+H7bGZHg4Z0vRV7DF9WehieoH76UAcrhlUvhRILAqMn2nwubTL0BGu9NngjYWxhpTXl2dnldMm+ZtyWj8x2dcRzLl//kOi/2n7cOJSalJeB2nu5LSOI4ojOQS4YqgtmFWIpVYxO3vDfbvd4SjfRUMk8QJajcdzwLzohHUR7R09mn3tbAlo7SipurNxCdNUlNb1inSswaabx6VV8VPcgk3n8Y7NqCEi2K+G4VLjn//UgGiwjvc4WWRyM+CxmJbnZ8nqgi1Ne0aWTM7HYXsPd/DSKodyhQo7z+vy5n0/B5p/cd8g+5a+/Oy8z1yJRCWcurd1dmTA3OQ1cXjr8Z6ddCr0ZlI5CHZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
